### ISSUE TITLE
Suggestbot showing 401 errors on incidents

### ISSUE THREAD

**Issue by Bruno-DaSilva** [grafana/incident-community#14]
**Describe the bug**
Suggestbot is getting a 401? Seeing this invalid api key error on incidents. Though I see suggestbot suggestions on the sidebar?

**To Reproduce**
1. Create an incident, drill or real.
2. Wait for suggestbot to trigger (few seconds)
3. See error

**Expected behavior**
Incident is created with no errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/8520801/181360092-7a714805-d8bc-4ee0-83c5-47e9cd14047a.png)

**Relevant system information**
* Grafana version v9.0.5 (1b595e434)
* Incident version v1.0.0-beta29

**Comment by Bruno-DaSilva** [comment]
I’ve tried uninstalling/reinstalling suggestbot and grafana integrations but still getting this invalid api key error on incidents.

**Comment by devinrcheevers** [comment]
Thanks for the bug report, these help make our product better, thank you! We're looking into this.

**Comment by matryer** [comment]
Thanks @Bruno-DaSilva this is the first time we've seen the bot misbehaving. 

@csmarchbanks Do you have any idea why this is happening?

And @clord lets work on a more subtle way of presenting these errors, they're a little overbearing. 😃

**Comment by matryer** [comment]
@aron-bordin how come the error message starts with 'HookRun.:'? Looks like it's missing something there.

**Comment by csmarchbanks** [comment]
Hmm, we just use the api key that is provisioned with the plugin. Is it possible someone deleted the api key and it needs to be reprovisioned?

**Comment by Bruno-DaSilva** [comment]
@csmarchbanks I suppose it's possible - though I don't –think- anyone has. Also if I click the suggestbot suggestions it still lists some suggested dashboards so it's like, half working?

**Comment by aron-bordin** [comment]
Thank you for your bug report, @Bruno-DaSilva! The issue has been identified, and we'll release the fix later today :)

**Comment by Bruno-DaSilva** [comment]
Thank you @aron-bordin @csmarchbanks !

**Comment by aron-bordin** [comment]
Hi @Bruno-DaSilva. A fix for this issue has been released and I'll be closing the issue for now. If you face something similar again, feel free to reopen it or to open a new issue :)

Thanks again for reporting it.

**Comment by Bruno-DaSilva** [comment]
Looks good to me on new incidents. FYI old incidents still have those nasty looking errors but that's NBD for us.
