### ISSUE TITLE
Embedded queries saving with incorrect timestamp, offset by current timezone

### ISSUE THREAD

**Issue by Bruno-DaSilva** [grafana/incident-community#15]
**Describe the bug**
My org's instance and browser is set to EDT. When I create a query and set the time range to something absolute or relative, I see the query preview as 'correct'. When I then SAVE this query, the time range is offset to 4 hours later. Each time I edit the query it sets itself to 4 hours later.

**To Reproduce**
1. Go to any incident in a grafana instance set to a non-UTC timezone (in my case, EDT) in a non-UTC browser (again, for me that's EDT).
2. Click the 'query' tab at the bottom of the incident to add a new query
3. Enter a query, for example avg(probe_duration_seconds{})
4. Set the time picker to any time period, for example (now-30m to now or 2022-04-22 10:34:06 to 2022-04-22 11:04:06)
5. Observe the preview is showing the 'correct' query result.
6. Click 'save'.
7. Observe the query shown is now offset by N hours and shows a different query result.

**Expected behavior**
When I save a query it should reflect the time range/time zone I saw in the preview.

**Screenshots**
<img width="909" alt="Screen Shot 2022-07-27 at 4 28 22 PM" src="https://user-images.githubusercontent.com/8520801/181366597-e05db2b0-067a-4d98-aba4-c1719d88106c.png">

<img width="817" alt="Screen Shot 2022-07-27 at 4 29 33 PM" src="https://user-images.githubusercontent.com/8520801/181366432-9d929cc5-062a-4678-a161-9922054d6ccb.png">

**Relevant system information**
Browser: Google Chrome 103.0.5060.134
Grafana: v9.0.5 (1b595e434)
Incident: 1.0.0-beta29
Browser timezone: EDT (UTC-4)
Organization timezone: America/Toronto (UTC-4)

**Comment by Bruno-DaSilva** [comment]
Seems be the exact same issue I reported in #9

**Comment by idk-92** [comment]
@Bruno-DaSilva  this should also be released sometime next week, apparently the previous fix was a very temporary means.

**Comment by idk-92** [comment]
@Bruno-DaSilva  if you could also close this issue if things look clear on your end, that'd be really helpful

**Comment by Bruno-DaSilva** [comment]
@idk-92 Unfortunately this is not solved from what I'm trying. Still offset by 4 hours on every save :(

**Comment by Bruno-DaSilva** [comment]
@idk-92 I'm available in the community slack if I can be of any help (getting access to our instance, screensharing, etc).

**Comment by idk-92** [comment]
@Bruno-DaSilva  reached out to you in the grafana community slack!

**Comment by Bruno-DaSilva** [comment]
Can confirm, this is working now. Thanks @idk-92 !
