### ISSUE TITLE
Embedded queries failing to load on refresh

### ISSUE THREAD

**Issue by Bruno-DaSilva** [grafana/incident-community#16]
**Describe the bug**
On load of an incident page, queries show as blank. Very occasionally they will render correctly. If you edit the query and save it, it renders correctly until you refresh again.

**To Reproduce**
1. Go to an incident with a created 'query'
3. Scroll down to the query panel. 
4. Observe that the query panel shows "No data or query"

**Expected behavior**
The query panel shows the saved query as a graph.

**Screenshots**
<img width="936" alt="Screen Shot 2022-07-27 at 4 40 16 PM" src="https://user-images.githubusercontent.com/8520801/181368321-45f90cff-d1d1-4066-be72-32e8a125ce6c.png">
<img width="927" alt="Screen Shot 2022-07-27 at 4 40 24 PM" src="https://user-images.githubusercontent.com/8520801/181368329-2ab4795e-b9c1-48f1-9944-4336e3e152fb.png">

**Relevant system information**
Browser: Google Chrome 103.0.5060.134
Grafana: v9.0.5 (1b595e434)
Incident: 1.0.0-beta29
Browser timezone: EDT (UTC-4)
Organization timezone: America/Toronto (UTC-4)

**Comment by Bruno-DaSilva** [comment]
I took a look in my dev console to see what's going on. I notice that there are TWO `/api/ds/query` endpoint requests being sent out - one of them returns results and one of them does not. If the zero-result query fails then the panel renders, if it succeeds then it shows no data.

The two requests are identical except for the payload:
** FAILING/NO RESULTS
```
{
    "queries": [
        {
            "refId": "A",
            "expr": "sum by (queue) (avg_over_time(rabbitmq_queue_messages{queue=~\"...\"}[5m:]))",
            "editorMode": "code",
            "range": true,
            "legendFormat": "__auto",
            "datasource": {
                "uid": "vSyGdhP7z",
                "type": "prometheus"
            },
            "queryType": "timeSeriesQuery",
            "exemplar": false,
            "requestId": "undefinedA",
            "utcOffsetSec": -14400,
            "interval": "",
            "datasourceId": 30,
            "intervalMs": 31536000000,
            "maxDataPoints": 0
        }
    ],
    "range": {
        "from": "2022-07-27T12:00:00.000Z",
        "to": "2022-07-27T20:45:59.000Z",
        "raw": {
            "from": "2022-07-27T12:00:00.000Z",
            "to": "2022-07-27T20:45:59.000Z"
        }
    },
    "from": "1658923200000",
    "to": "1658954759000"
}
```
<img width="765" alt="Screen Shot 2022-07-27 at 4 46 02 PM" src="https://user-images.githubusercontent.com/8520801/181369056-96832adb-3831-4f53-b1a8-5b950fc8729b.png">


SUCCESSFUL
```
{
    "queries": [
        {
            "refId": "A",
            "expr": "sum by (queue) (avg_over_time(rabbitmq_queue_messages{queue=~\"...\"}[5m:]))",
            "editorMode": "code",
            "range": true,
            "legendFormat": "__auto",
            "datasource": {
                "uid": "vSyGdhP7z",
                "type": "prometheus"
            },
            "queryType": "timeSeriesQuery",
            "exemplar": false,
            "requestId": "undefinedA",
            "utcOffsetSec": -14400,
            "interval": "",
            "datasourceId": 30,
            "intervalMs": 30000,
            "maxDataPoints": 809
        }
    ],
    "range": {
        "from": "2022-07-27T12:00:00.000Z",
        "to": "2022-07-27T20:45:59.000Z",
        "raw": {
            "from": "2022-07-27T12:00:00.000Z",
            "to": "2022-07-27T20:45:59.000Z"
        }
    },
    "from": "1658923200000",
    "to": "1658954759000"
}
```
<img width="846" alt="Screen Shot 2022-07-27 at 4 46 12 PM" src="https://user-images.githubusercontent.com/8520801/181369062-22eff769-07ff-43b0-9550-0634d70dafd9.png">

**Comment by Bruno-DaSilva** [comment]
And here's an example of the no data query failing and the panel rendering

<img width="1082" alt="Screen Shot 2022-07-27 at 4 10 47 PM" src="https://user-images.githubusercontent.com/8520801/181369904-f4a37813-a1c5-4786-8304-663f8d1be5a2.png">
<img width="1083" alt="Screen Shot 2022-07-27 at 4 08 50 PM" src="https://user-images.githubusercontent.com/8520801/181369929-677db619-22f3-4cb7-ac98-7808460ee53c.png">

**Comment by devinrcheevers** [comment]
Thanks for a great bug report, we'll look into this!

**Comment by matryer** [comment]
@Bruno-DaSilva What a great report, thank you so much. We'll take a look and see if we can figure out what's going on here. cc @idk-92

**Comment by idk-92** [comment]
@Bruno-DaSilva Thanks for the awesome write up! This should be resolved with the next release.

**Comment by idk-92** [comment]
@Bruno-DaSilva if you don't mind closing out this issue if things look good on your end!

**Comment by Bruno-DaSilva** [comment]
Can confirm, looks like it's working. Thanks all!
