### ISSUE TITLE
Feature teams integration

### ISSUE THREAD

**Issue by NissesSenap** [grafana/incident-community#30]
**Describe the feature**
Currently there is no teams integration support.
https://grafana.com/docs/grafana-cloud/incident/integrations/

Teams is a big part of many companies day to day workflow and it would make sense if teams would be available.

This functionality for example exists for grafana onCall so it would be nice to be consistent between the different modules in grafana.

**Comment by NissesSenap** [comment]
This already exist as a discussion: https://github.com/grafana/incident-community/discussions/21

**Comment by fcjack** [comment]
hi @NissesSenap, could you help us [here](https://github.com/grafana/incident-community/discussions/21#discussioncomment-4838360).

**Comment by NissesSenap** [comment]
I will take a look directly

**Comment by fcjack** [comment]
Thanks @NissesSenap, if you know more people interested in this feature, please share this discussion we are really interest to hear from users.

**Comment by matryer** [comment]
Hey @NissesSenap - we'd love your opinions here, if you have some time? https://github.com/grafana/incident-community/discussions/49

**Comment by brngates98** [comment]
this would be super amazing to get teams integrations

**Comment by fcjack** [comment]
Hello everybody, thank you all for the inputs and patience on this feature.
I have good news, we released the new Microsoft Teams integration today for a public preview.
You can try out the integration and work with Incidents inside Ms Teams \o/

The solution adopted was the number 2 in the [discussion](https://github.com/grafana/incident-community/discussions/21#discussioncomment-4838360), so each incident will have your own thread to work on!
We will appreciate any feedback in this state and we will continue improving the tool.
