### ISSUE TITLE
Slackbot 🤖 reaction does not save messages from Slack users without Grafana accounts

### ISSUE THREAD

**Issue by andy-paine-numan** [grafana/incident-community#31]
**Describe the bug**
Reacting with 🤖 to messages in Slack from users without Grafana accounts does not seem to save messages to the incident log

**To Reproduce**
1. Create an incident
2. Have a user without a Grafana account post in the created channel
3. React with 🤖 to the message

**Expected behavior**
The message the user posted to appear in the incident log

**Actual behavior**
The message does not appear in the incident log

**Relevant system information**
Grafana: v.9.20
Incident: v1.0.12

**Comment by aron-bordin** [comment]
Hi @andy-paine-numan, Sorry for the late reply. This issue has been fixed today and we'll release the fix soon

**Comment by idk-92** [comment]
Closing this issue as this has been resolved, please let us know if is still a problem and we'll reopen this issue
