### ISSUE TITLE
Unable to view incidents after being resolved

### ISSUE THREAD

**Issue by JacobusH** [grafana/incident-community#33]
**Describe the bug**
After making an incident I am unable to view the incident in the overview. 

**To Reproduce**
1. Create an incident 
2. Go to overview, incident is not there
3. Go back to incident via url (the url still works directly)
4. Resolve incident
5. Incident is still not showing in the overview

**Expected behavior**
The incident should appear in the overview

**Screenshots**

![screenshot_2022-10-26-174649](https://user-images.githubusercontent.com/12116067/198073543-5e37f0d9-5a61-4a42-b654-7e7e87ba089e.png)
![screenshot_2022-10-26-174609](https://user-images.githubusercontent.com/12116067/198073546-3d610b09-05fc-4f18-b650-caf324755df0.png)

**Relevant system information**
Test on Chromium and Firefox
Grafana v9.2.1-cab7049dd1

**Comment by aron-bordin** [comment]
Hi @JacobusH ! Thank you for reporting this. We are working to push a fix for this issue soon :) I'll let you know once it's deployed

**Comment by idk-92** [comment]
@JacobusH This should be resolved with the latest plugin version of v1.0.17. Thanks for identifying this issue!
