### ISSUE TITLE
Grafana Alerting 

### ISSUE THREAD

**Issue by vaibhav-771** [grafana/incident-community#38]
I Have an dashboard and which consist of the one panel and on the panel there are the 3 queries  and the alerts are configured on all the 3 three queries  and  if an  alert is come in any of the one query then the notification is come on the slack and the slack notificaton consist of the alert status and the alert name then when we click on that link we will redirect to the dashboard then i want to know the url of that through which we will redirect to that dashboard . Internally which url is coming on the slack from grafana through which the webhook notifiation is attched .

**Comment by twu** [comment]
👋 Apologies for the late reply,

If I understood you correctly this seems to be an issue with configuring Alerting and Templates (maybe [[0](https://community.grafana.com/t/define-link-on-grafana-template/78499/2)] helps?). I'm closing this issue as it is not related to incident however I'm sure somone on the [Grafana Community Forum: Alerting](https://community.grafana.com/c/support/alerting/60), [Grafana Community Slack](https://slack.grafana.com/) and/or specifically the [Grafana Community Slack `#alerting`](https://grafana.slack.com/archives/C043CEX9MBK) channel is able to help you out. HTH 🙇
