### ISSUE TITLE
Links from Slack are malformed

### ISSUE THREAD

**Issue by dannykopping** [grafana/incident-community#39]
**Describe the bug**
Messages ingested from Slack have the format `link|<title>`, and when these links are clicked they contain `|<title>`

**To Reproduce**
1. Go to an incident
1. Click on a link from a message ingested from Slack
1. Link does not work because it is malformed

**Expected behavior**
The URL should not be malformed.

**Screenshots**
![image](https://user-images.githubusercontent.com/373762/203976944-3622d7dd-b603-4bae-9303-b318897e35e3.png)
The link, when copied, has this format: `https://....%7Clink`.

**Relevant system information**

Grafana: v9.4.0-42921pre (d5274dfdda)
Incident: v1.0.23

**Comment by matryer** [comment]
Thanks @dannykopping - we are actively working on solving this.

**Comment by matryer** [comment]
@dannykopping we have a fix for this going out this week, would you be up for testing this a little for us, and providing some feedback?

**Comment by dannykopping** [comment]
@matryer certainly, let me know when it's live and i'll create a drill incident

**Comment by matryer** [comment]
If you could cause an actual incident in your systems instead, that'd be much appreciated. :)

**Comment by idk-92** [comment]
Closing this issue as this has been resolved, please let us know if is still a problem and we'll reopen this issue
