### ISSUE TITLE
Support Google Advanced Protection

### ISSUE THREAD

**Issue by grobie** [grafana/incident-community#44]
**Describe the bug**
The Grafana Incidents application is not verified under [Google's Advanced Protection program](https://landing.google.com/advancedprotection/) and can't be installed:

> ### Access blocked: Grafana Incident is not approved by Advanced Protection
>
> The Advanced Protection Program performs additional security checks to safeguard your account data, and it hasn't approved this app.
>
> If you want to allow Grafana Incident access to your data, you can reach out to the app [developer](https://accounts.google.com/) and encourage them to submit the app for verification. [Learn more about this error](https://support.google.com/accounts/answer/7539956#zippy=%2Ccan-i-still-use-sign-in-with-google%2Ccan-i-use-non-google-apps-services-or-apps-script-with-advanced-protection)

**To Reproduce**
1. Sign-in into a Google account with Advanced Protection enabled (e.g. accounts with admin privileges)
2. Follow the Grafana Incident wizard
3. Click on "Install Google Workspace"
4. See error message

**Expected behavior**
Able to install the Google Workspace integration.

**Screenshots**
![image](https://user-images.githubusercontent.com/3432/208497651-143fd8e3-dc06-47f6-acaf-8e110db20147.png)

**Relevant system information**
Grafana [v9.3.2-45365 (ef5286dd77)](https://github.com/grafana/grafana/blob/main/CHANGELOG.md)

**Comment by matryer** [comment]
Thanks @grobie - we're working on this.

**Comment by matryer** [comment]
Update: Work is progressing on this, we are meeting with Google to get it resolved asap.
