### ISSUE TITLE
Incident presentation order does not respect start / end date

### ISSUE THREAD

**Issue by dstockhammer** [grafana/incident-community#46]
**Describe the bug**
The order of incidents in the incidents presentation appears to be the order of creation of the Grafana Incident, not the overridden values. See also https://github.com/grafana/incident-community/issues/45

As a side note (maybe not a bug), I would expect the start and end dates to be shown in the timeline, since that's key information.

**To Reproduce**
1. Create some incidents
2. Override start and end dates

**Expected behavior**
The incidents presentation should be ordered by the start dates, not the incident creation dates

**Relevant system information**
- [Cloud Pro (Licensed)](https://grafana.com/products/enterprise/?utm_source=grafana_footer) [v9.3.2-67a213dc85 (67a213dc85)](https://github.com/grafana/grafana/blob/main/CHANGELOG.md)
- Incidents v1.0.26

**Comment by paulcoghlan** [comment]
Hi again @dstockhammer.  As for https://github.com/grafana/incident-community/issues/47, we have a new version (1.0.29) which should have resolved the issue.  Would you mind checking again?

Thanks again for your patience.

**Comment by dstockhammer** [comment]
Hi there, at quick glance it looks like the issue is resolved, thanks!
