### ISSUE TITLE
Slack /incident does not work in the preview

### ISSUE THREAD

**Issue by BitProcessor** [grafana/incident-community#5]
See attached screenshot, this is on v1.0.0-beta9

The `/incident` command as proposed does not work
Instead, one has to use `/incident-preview-au` (see screenshot)
Not sure where the "au" stands for?

![Screenshot 2022-04-08 at 14 05 16](https://user-images.githubusercontent.com/50638541/162433721-a0d98621-f2a4-4dd3-9ac6-2d939dbb70d4.png)

![Screenshot 2022-04-08 at 14 17 12](https://user-images.githubusercontent.com/50638541/162434008-2d77c1d7-2c4c-4cd8-8188-9f9ff5147ccb.png)

**Comment by aron-bordin** [comment]
Hi @BitProcessor! During the beta, we'll be using `/incident-preview-*` chatbots. We'll make sure to update our docs/helps to keep it clear :) They will be renamed to `/incident` in the future.

> Not sure where the "au" stands for?
It was a typo from our side. We fixed and it should be available as `/incident-preview-eu0` now :)

**Comment by matryer** [comment]
@BitProcessor @aron-bordin and I are going to look at fixing this asap, so you'll be able to use `/incident` as you'd expect.

**Comment by matryer** [comment]
@BitProcessor we updated the commands to use `/incident` now, can you try this and let us know if that's working for you?

**Comment by BitProcessor** [comment]
@matryer tested and now works as expected 👍🏻
