### ISSUE TITLE
Incident duration does not respect start / end date in presentation mode

### ISSUE THREAD

**Issue by dstockhammer** [grafana/incident-community#50]
Please see https://github.com/grafana/incident-community/issues/45 for a description of the issue. 

The **presentation mode** still shows the wrong duration.

**Comment by paulcoghlan** [comment]
@dstockhammer - apologies for not replying sooner. 

It looks like the fix for https://github.com/grafana/incident-community/issues/45 wasn't applied to presentation mode. I will let the team know and we will get this fixed.

**Comment by paulcoghlan** [comment]
Hi @dstockhammer - as for https://github.com/grafana/incident-community/issues/47, we've fixed the start/end time in presentation mode, would you mind taking a look again?

Thanks again for the feedback.

**Comment by idk-92** [comment]
Closing as this should also be resolved from previous release Let us know if things are not in order and we can reopen this issue
