### ISSUE TITLE
Feature request: Show incident start and end date in presentation mode

### ISSUE THREAD

**Issue by dstockhammer** [grafana/incident-community#51]
Please show the incident start and end dates in the presentation mode. We use the UI for weekly ops reviews; in my opinion start and end dates are key pieces of information that should be included on the overview page. For the detailed timeline it's ok to navigate to the individual incident detail pages.

**Comment by paulcoghlan** [comment]
Hi @dstockhammer - as discussed we have now changed presentation mode to show incident start and end datetimes. I have an incident that was opened in January and closed today, but I've changed the end date to be much earlier:

<img width="954" alt="Screenshot 2023-02-23 at 09 48 07" src="https://user-images.githubusercontent.com/805060/220872986-69c4083c-68d9-4128-944b-af225a687b73.png">

<img width="778" alt="Screenshot 2023-02-23 at 09 49 56" src="https://user-images.githubusercontent.com/805060/220873089-d735eede-e735-472a-8241-4f675be5e1df.png">

Hope this is as expected?

**Comment by idk-92** [comment]
Closing this as this is resolved, also next release will contain cleaner formatting
