### ISSUE TITLE
Click on "Specify incident severity" doesn't do anything

### ISSUE THREAD

**Issue by davkal** [grafana/incident-community#54]
**Describe the bug**
Cannot set severity by clicking on `Specify incident severity`

**To Reproduce**
1. Declare incident
2. Click on `Specify incident severity` on the right hand side with all the tasks
3. Nothing happens

**Expected behavior**
Some way to select the severity.

After thinking a bit about this, this might be to assign a person to figure out the severity. But in my understanding the verbiage is so clearly directed towards setting the severity right there, that I find hard to think of the other thing. Even after I assigned myself as that person, I still want to click on `Specify incident severity` and nothing happens. Perhaps this just needs a copy change.

**Screenshots**

<img width="480" alt="Screenshot 2023-02-22 at 16 53 45" src="https://user-images.githubusercontent.com/859729/220679463-5208e3c5-0294-442e-9797-a957ec809fb9.png">

**Comment by clord** [comment]
agreed it feels a bit like button copy, with the imperative language used.

**Comment by matryer** [comment]
@clord do you have an idea of how we could address this?

**Comment by clord** [comment]
fundamentally, it's not reading as a task list, but as a button or action. The wording on these auto-tasks could somehow help to indicate that it's a task list. 

Alternatively, some tasks might have associated resolution mechanism. for example, severity could have the severity dropdown menu right there, together with the task. Assigning roles could be like this, too, and in theory we could have others like github issues with associated mechanisms (when the issue closes, the task resolves as done)

**Comment by mcschatz** [comment]
None of the automated actions in the task list are actionable. We should consider removing them from the task list. We already have calls to action for assigning the commander, investigator, and severity elsewhere in the UI.

cc: @anavss

**Comment by anavss** [comment]
Agree! My understanding is that @clord already worked it, also because it was cluttering the task page and making it less useful. It looks like the PR has been merged, maybe it's just depending on the next release? Issue: https://github.com/grafana/incident/issues/5424

**Comment by anavss** [comment]
can confirm that we are no longer showing these tasks by default, so closing this issue 

![Screenshot 2024-06-05 at 3 10 40 PM](https://github.com/grafana/incident-community/assets/86568531/47b96c66-0a71-4215-b3a2-dde826a06eba)
