### ISSUE TITLE
Unable to create incidents . Error- roomPrefix is required

### ISSUE THREAD

**Issue by nshampur** [grafana/incident-community#58]
**Describe the bug**
We recently signed up for a Grafana cloud account and are evaluating Grafana incident as it seems extremely appealing to our needs. 

However we seem to be having issues creating incidents. 

**To Reproduce**
1. Go to Incidents
2. Click on New Incident 
3. Fill in bare essentials information 

![image](https://user-images.githubusercontent.com/4503683/231242232-f508f056-464a-434e-8ec7-8f197389d954.png)

**Expected behavior**
Be able to create incidents and perform a drill

**Relevant system information**
Tried Chrome and Firefox .
Grafana Cloud

**Comment by aron-bordin** [comment]
hi @nshampur !

We released some fixes for these issues yesterday. Could you try again, please?

**Comment by nshampur** [comment]
This looks to be resolved now.  Thanks for addressing.
