### ISSUE TITLE
Onboarding shows 'what's new' even in the empty state

### ISSUE THREAD

**Issue by devinrcheevers** [grafana/incident-community#59]
**Describe the bug**
Onboarding shows 'what's new' even in the empty state

<img width="1687" alt="Screenshot 2023-04-12 at 5 08 14 PM" src="https://user-images.githubusercontent.com/85312870/231612962-03fe5df3-19d7-4e47-9d00-4dfaa1eedeba.png">

**To Reproduce**
Try out empty state of Grafana Incident

**Expected behavior**
What's new box isn't visible

**Comment by reemtariqq** [comment]
Thanks @devinrcheevers , ew deployed a fix today that will close this issue
