### ISSUE TITLE
Cancelling a Slack integration request doesn't let you restart the setup process

### ISSUE THREAD

**Issue by indygriffiths** [grafana/incident-community#6]
**Describe the bug**
When I went to install the Slack integration, the Slack OAuth prompt said that only workspace admins for our Slack org could install the app, so I had to go back to Grafana Incident.

Since the setup process wasn't completed, the main page of Grafana Incident doesn't show the blue Install button for the Slack integration anymore, but "Installing..." and a loading spinner regardless of refreshing/clearing the cache/logging out and back in. 

Nothing in the console that I could see showing an error. Basically stuck since I can't do anything without setting up Slack.

**To Reproduce**
1. Go to Grafana Incident on a fresh install
2. Start the Slack integration process, but do not complete it (close the tab)
3. Go back to Grafana Incident and refresh the page
4. You should see an "Installing..." loading spinner with no option to try the installation again.

**Expected behavior**
When the installation of the Slack integration is cancelled, the option to install is present on the main dashboard in Grafana Incident.

**Screenshots**
<img width="881" alt="image" src="https://user-images.githubusercontent.com/32345766/163922973-c8a2eb86-a0b2-4fca-8404-8bfb94ff426f.png">

**Relevant system information**
Chrome, Grafana v8.4.6 (hosted on Cloud)

**Comment by aron-bordin** [comment]
Hi @indygriffiths, thank you for reporting this issue! I was able to reproduce it locally and we'll be publishing the fix soon. I'll let you know once it is fixed :)

**Comment by aron-bordin** [comment]
@indygriffiths, we deployed the fix a few minutes ago. Could you check this and let us know if that's working for you? :)

**Comment by indygriffiths** [comment]
Confirmed fixed, cheers for the quick turnaround!
