### ISSUE TITLE
Incidents are not able to be resolved

### ISSUE THREAD

**Issue by carozuniga** [grafana/incident-community#65]
**Describe the bug**
Incidents remain open even when clicking on the "Resolved" button. an EOF warning appears as a notification. 
**To Reproduce**
1. Create an incident.
2. Click on the "Active" button.
3. Click on "Resolved" to update the incident status.
4. Click on "Resolve with summary" button on the pop up page. 
5. EOF error
6. Incident remains "Active"

**Expected behavior**
Incident goes from the active state to resolved.
**Screenshots**
![image](https://github.com/grafana/incident-community/assets/19275333/25204406-fe67-427c-ae71-e30555994c30)
**Relevant system information**

**Comment by aron-bordin** [comment]
Hi @carozuniga 

thanks for reporting it. We are currently working on it, and we'll be releasing a fix soon! We'll let you know once it's fixed

**Comment by aron-bordin** [comment]
hi @carozuniga 

we released the fix for this issue. can you check if you can resolve your incident now?

thanks for reporting it 🚀

**Comment by carozuniga** [comment]
Hi @aron-bordin it seems to be working correctly now! thanks
