### ISSUE TITLE
Expect Array , received null when attaching context to incident

### ISSUE THREAD

**Issue by dmigl-craneww** [grafana/incident-community#69]
**Describe the bug**
When documenting an incident I got buggy behavior out of the attach context button.

**To Reproduce**
1. Go to Alerts & IRM -> Incidents ->  <some-existing-incident
2. Click `+ Attach` to add context to an incident
3. Then Remove context which was just added
4. Then retry attaching context and get the following error:

```
[
  {
    "code": "invalid_type",
    "expected": "array",
    "received": "null",
    "path": [
      "incidentContext",
      "metadata"
    ],
    "message": "Expected array, received null"
  }
]
```
**Expected behavior**
I expect the array to be empty as opposed to null. It being null does not allow for new contexts to be attached to an incident

**Screenshots**

![image](https://github.com/grafana/incident-community/assets/124075900/2b3e6de0-573e-4b95-8f9f-402dc5742bfd)
![image](https://github.com/grafana/incident-community/assets/124075900/92ea007f-3650-44b4-bcab-bf12afe31959)

**Relevant system information**
Grafana Cloud

**Comment by reemtariqq** [comment]
Hi @dmigl-craneww 

We released the fix for this issue. can you check if you can attach a url without errors now ? 

thanks for the reporting 🚀

**Comment by dmigl-craneww** [comment]
Looks to be working fine 👍🏽 , thanks!
