### ISSUE TITLE
Wrong timezone used in Slack image when incident is declared

### ISSUE THREAD

**Issue by indygriffiths** [grafana/incident-community#7]
When Grafana Incident posts into the designated channel that a new incident was declared, the picture shows the incident declaration time in UTC rather than the local timezone of the user who declared the incident or the org timezone in Grafana. For us in New Zealand this is a 12 hour offset.

See the timestamp of the Slack message compared to the one in the image (note the ~13 minute delay was from unmarking the incident as a drill):

<img width="693" alt="image" src="https://user-images.githubusercontent.com/32345766/164110528-4632c48b-dff1-4390-9814-1e9311251c31.png">

**Comment by matryer** [comment]
@indygriffiths thanks for this, do you think it should follow the org's timezone? Either way, we'll include the timezone on the timestamp.

Which would you prefer?

* `NZST`
* `UTC+12`
* `NZST (UTC+12)`

**Comment by indygriffiths** [comment]
Within our org we tend to use the identifier when expressing timezones so `NZST` (which switches to `NZDT` during daylight savings)

**Comment by matryer** [comment]
@indygriffiths We tweaked this thanks to your feedback, have you noticed an improvement?

**Comment by clord** [comment]
Closing, we did lots of work on this.
