### ISSUE TITLE
Incorrect time stamp on incidents IRM

### ISSUE THREAD

**Issue by brngates98** [grafana/incident-community#72]
**Describe the bug**
Incident Time for Declared incidents is not correct.

**To Reproduce**
We did a test real incident and noticed time stamp was wrong, did a drill incident and time stamp was saying 1:36 but its 9:36 when we did that. Time zone in grafana is set to America/New York

**Expected behavior**
Time to be correct.

**Screenshots**
![image](https://github.com/grafana/incident-community/assets/59444489/3f85d4e8-adbb-46bf-a8cf-482a8b48a295)
![image](https://github.com/grafana/incident-community/assets/59444489/7cece697-6629-4d47-a9c0-1c1aa423159a)

**Relevant system information**
IRM Pro,Grafana v10.1.0-cloud.3.2a3062e8 (2a4a96c8)

**Comment by fcjack** [comment]
Hi @brngates98 ,

thanks for using Grafana Incidents and reporting this issue.
We are working to fix this issue and include in the next release.
