### ISSUE TITLE
Feature Request: Ability to page people from Grafana Incident UI

### ISSUE THREAD

**Issue by Hronom** [grafana/incident-community#77]
We need possibility to page people(e.g. OnCall) directly from Grafana Incident UI.

**Comment by twu** [comment]
@Hronom 👋 

This is now possible now with the latest version of Incident and a Direct Paging[^2] setup done in OnCall. You can read more about it in the introductory article [_Easily page participants to accelerate incident response in Grafana IRM_](https://grafana.com/blog/2023/12/13/easily-page-participants-to-accelerate-incident-response-in-grafana-irm/) or on the Grafana Blog[^1] or the relevant parts of the Grafana IRM[^2][^3] documentation.

HTH :)


[^1]: https://grafana.com/blog/2023/12/13/easily-page-participants-to-accelerate-incident-response-in-grafana-irm/
[^2]: [OnCall: Page People Manually](https://grafana.com/docs/oncall/latest/integrations/manual/#page-people-manually)
[^3]: [Incident: Add Participants](https://grafana.com/docs/grafana-cloud/alerting-and-irm/incident/manage/add-participants/)

**Comment by matryer** [comment]
Hey @Hronom have you had chance to play with this yet? We're keen to hear your feedback.

**Comment by Hronom** [comment]
@twu and @matryer thank you a lot! This works now
