### ISSUE TITLE
Unable to edit/remove comments in timeline

### ISSUE THREAD

**Issue by Hronom** [grafana/incident-community#79]
**Describe the bug**
Can't edit notes in timeline or remove them

**Screenshots**
![image](https://github.com/grafana/incident-community/assets/429993/e8234322-533c-4bdf-a29f-6ef89c03408b)

**Relevant system information**
Grafana v10.2.0-60477 (6f785f72), grafana cloud

**Comment by reemtariqq** [comment]
Hi @Hronom i believe this has been fixed and you can edit/remove notes from the timeline. would you try again and let us know if you are still facing the issue ?

**Comment by Hronom** [comment]
@reemtariqq thank you! It works
