### ISSUE TITLE
Pills with links disapear from notes when change default timezone for the org

### ISSUE THREAD

**Issue by Hronom** [grafana/incident-community#80]
**Describe the bug**
Pills with links disappear from notes when change default timezone for the org.

```
Grafana v10.2.0-60853 (0c081633)
```

**Comment by twu** [comment]
@Hronom 👋 

I tried reproducing this with Grafana Incident `v1.32.1` and Grafana `Grafana v10.3.0-64399 (09445e0ecc)` but no luck. I took the following steps: 

0. Set my Orgs default TZ to UTC.
1. Declared an incident
2. Added a Note with a Pill containing an URL (`https://www.grafana.com`).
3. Set my Orgs default TZ to UTC+12:00.
4. Refreshed the Incident page.

The pill and its contents are properly rendered and are still showing up on my end. Did I miss something important here? Thank you! 🙇
