### ISSUE TITLE
Cannot open Slack link

### ISSUE THREAD

**Issue by buro9** [grafana/incident-community#82]
**Describe the bug**

When I view an incident, on the page `/a/grafana-incident-app/incidents/1068` there is a link to the Slack channel where the incident is being discussed.

This link is in the form `slack://channel?id={channelid}&team={team}`.

As the Slack app does not know which browser to open when there are links in Slack, I do not use the Slack app. This is common for developers, especially developers that do frontend work who will have more than 1 browser installed and typically have 2 or 3 browsers.

Without the Slack app installed, that link does not do anything.

The Slack app is not required to use Slack and shouldn't be assumed to be present, further Slack themselves provide a forwarding page that if you used the web URI link to the Slack channel it would open it in the app _if_ the Slack app were installed.

**To Reproduce**

1. Go to an open incident whilst not having the Slack app installed
2. Click the Slack link
3. Nothing happens

**Expected behavior**

I expect clicking the Slack link whilst in a web browser where I have Slack open and fully authenticated would just open a new tab with the incident Slack channel.

**Screenshots**
None required.

**Relevant system information**
Installed and latest: Firefox, Chrome, Safari, Windows, Linux, Mac, Grafana, Grafana Incident.
Absent: Slack app on any platform.

**Comment by buro9** [comment]
Could also consider adding a preference for the user as to whether this opens the app or the web page.

**Comment by matryer** [comment]
thank you @buro9 - we've fixed this, and it'll appear in our next release.
