### ISSUE TITLE
Unable to paste text into Incident Note

### ISSUE THREAD

**Issue by Westhuyzen** [grafana/incident-community#84]
With multiple browsers, unable to paste text into an incident in Grafana Cloud IRM. This appears to be new in the last couple of weeks.

**To Reproduce**
1. Go to an incident
2. Click in note text box
3. Paste (from clipboard of a small amount of plain text)
4. Nothing happens

**Expected behavior**
Paste succeeds

**Screenshots**
n/a

**Relevant system information**
_Browser, Grafana version, etc._

**Comment by twu** [comment]
👋 @Westhuyzen, thank you for taking the time to report this. I can reproduce this locally and raised it with the team immediately. Will post again once the fix is in `prod`. Thank you! :)

**Comment by SBejga** [comment]
Besides pasting, Copy is also not working.

**Comment by clord** [comment]
We have a local fix. next release should address this.
