### ISSUE TITLE
Incident Page Incident Duration is inaccurate

### ISSUE THREAD

**Issue by asreich** [grafana/incident-community#89]
**Describe the bug**

When viewing an Incident Page, the duration is incorrect in the bottom right of the overall panel:

![image](https://github.com/grafana/incident-community/assets/11779260/0d3606f7-49b3-4d93-adc4-12c6fd4c94fc)

This incident lasted for under a minute because it was a test and the tooltip for it shows:

![image](https://github.com/grafana/incident-community/assets/11779260/28eca510-8581-454e-9829-797be08b7e2d)

And it is still continuing to tick upwards. This leads me to believe it is tracking "time since incident".

**To Reproduce**
1. Declare incident
2. Wait a minute, resolve incident
3. Come back 30 minutes later
4. See Incident apparently lasted for 31 minutes

**Expected behavior**

I expect the incident duration to not change as time passes after it has been resolved.

The Insights page correctly has the incident duration (although it is lacking the commander/investigator data). I think both incident duration and time since incident could be useful, but they are unfortunately being overlapped here.

**Relevant system information**

Grafana Cloud v10.4.0-65875 (b758b91e84)
Grafana IRM v1.37.4

**Comment by clord** [comment]
We have a fix pending for this. hopefully in the next release. thanks for the report!

**Comment by asreich** [comment]
Confirmed fixed, thank you!
