### ISSUE TITLE
Character in Teams team name breaks integration search function

### ISSUE THREAD

**Issue by asreich** [grafana/incident-community#90]
**Describe the bug**

When trying to configure the MS Teams integration for IRM we noticed that if we spelled out out team name in the search bar "DM&T" it breaks the search panel and causes an error.

**To Reproduce**
1. Install MS Teams integration on IRM Integrations page
2. Click on "Run when an event fires"
3. Start searching for a team name with an "&" character in it

**Expected behavior**

The "&" character, nor any other valid special characters supported in MS Teams team names break this search function.

**Screenshots**

![image](https://github.com/grafana/incident-community/assets/11779260/d093eb82-c9bd-41b9-bd05-9d591455e7fc)

**Relevant system information**

Grafana Cloud v10.4.0-65875 (b758b91e84)
Grafana IRM v1.37.4

**Comment by twu** [comment]
👋 Thank you for reaching out and reporting the issue! We have a fix ready which should go out with the next release. I will let you know once that is done :)

**Comment by twu** [comment]
@asreich We just released `v1.38.0` which includes a fix for this issue 🤞 Thank you again for reporting and please let us know if this does or doesn't fix the issue 🙇

**Comment by asreich** [comment]
Confirmed fixed, thank you!
