### ISSUE TITLE
Paging accept/decline window does not disappear

### ISSUE THREAD

**Issue by asreich** [grafana/incident-community#91]
**Describe the bug**

I tried inviting my teammate to an incident and when they got to the incident page and clicked "accept", they joined the incident but the dialogue box wouldn't go away no matter how many times they clicked "accept". It only disappeared when they clicked "dismiss".

**To Reproduce**
1. Create incident
2. Add user to incident
3. User tries to click accept on incident
4. User is added to incident but dialogue box doesn't disappear

**Expected behavior**

The dialogue box should disappear after accepting/declining the incident

**Relevant system information**

Grafana Cloud v10.4.0-65875 (b758b91e84)
Grafana IRM v1.37.4

**Comment by clord** [comment]
https://github.com/grafana/incident-community/issues/94 is the same issue as this.

**Comment by asreich** [comment]
@clord Hey there, just to confirm. Do you mean the fix/reason it's happening is the same? The dialogue box in this issue is a separate button/view than what is in #94. I can get you a screenshot later today.

**Comment by clord** [comment]
Hey, found the problem, we should get this fix out for the next release.
