### ISSUE TITLE
Option to invite participants not visible on Grafana Incident details page

### ISSUE THREAD

**Issue by DorianOlympia** [grafana/incident-community#92]
**Describe the bug**
According to documentation: https://grafana.com/docs/grafana-cloud/alerting-and-irm/incident/manage/add-participants/
In order to manually add participants to an incident one have to use "paged participants" section on the UI. The problem is that for some reason this section recently disappeared from my Grafana Cloud UI.

Even when I open some older incidents for which I successfully paged people in, this section is still not visible.

I assume there is either a bug that does not show this section on UI or there is some condition that I need to meet in order to see this section, that documentation do not mention.

**To Reproduce**
Declare an incident/drill and open it in order to add participants.

**Expected behavior**
Section 'paged participants' mentioned in the documentation is visible and works.

**Screenshots**
expected:
![image](https://github.com/grafana/incident-community/assets/10976785/33f1d968-712c-4c60-ae1a-984cbfa41842)

actual:
![image](https://github.com/grafana/incident-community/assets/10976785/74a37b47-671e-4a6e-be03-a27f579121c9)

**Relevant system information**
Grafana Cloud Incident v1.37.4, Google Chrome

**Comment by matryer** [comment]
Hey @DorianOlympia thanks for reaching out - you're right, the feature flag got turned off by mistake. We'll get this fixed today.

**Comment by DorianOlympia** [comment]
Awesome, thanks for quick response

**Comment by reemtariqq** [comment]
Hi @DorianOlympia  we released a fix yesterday that should fix this issue, would you please try again ?
