### ISSUE TITLE
Commander/Investigator Fields not populating on Insights Dashboard

### ISSUE THREAD

**Issue by asreich** [grafana/incident-community#97]
**Describe the bug**

I am aware the Insights dashboard is in the **Experimental** lifecycle phase. The commander/investigator fields do not appear to be populating on the insights page, nor in the raw Incident datasource data. I would also love for the Observers counter to be populated.

**To Reproduce**

1. Go to any individual Incident page and see that commander/investigator have been assigned one more more times
2. Go to Incident Insights page or query Incident data in Explore
3. Notice commander/investigator fields are "No" or "0"

**Expected behavior**

The commander/investigator/observer fields should be populated with data

**Screenshots**

Raw incident datasource data
![image](https://github.com/grafana/incident-community/assets/11779260/8a0454f4-fb21-428c-b9fb-f9ec2cda973d)

Incident Dashboard panel
![image](https://github.com/grafana/incident-community/assets/11779260/28b8d26a-b783-47bd-a9ca-7ca3c74c5694)

**Relevant system information**

Grafana v10.4.0-65875 (b758b91e84)
Incident v1.38.0

**Comment by twu** [comment]
👋 Thank you for reporting things! We really appreciate it 🙇 

Yes, with the rollout of custom roles earlier this month we broke the role-based queries and both panels in the Insights datasource/dashboard. We are aware of it, but we have a few more potential breaking changes coming up very soon and a possible rewrite of the entire thing using [Grafana Scenes](https://github.com/grafana/scenes).

I will give a quick look to see if there is an easy fix we can do to make this work again in the datasource at least for the default roles and get back to you once I know more. 🙇

**Comment by asreich** [comment]
Great, thanks. If there's a quick fix that'd be nice but this isn't urgent. I'm trying to show this off to various people and some of these questions have come up.

**Comment by idk-92** [comment]
There's been a big switch over to utilize the scenes framework which handles being able to dynamically cater to the "custom roles" environment that are defined in the incident settings page. The table in the insights view has the role and the person assigned to the incident and should be released within the next week or so.
