### ISSUE TITLE
Hyperlink text box spawns partially obscured in the top left corner

### ISSUE THREAD

**Issue by asreich** [grafana/incident-community#98]
**Describe the bug**

I pasted the link to our Post Incident Report in the Incident timeline textbox and saw the hyperlink hops to the top corner. This happens in both Chrome and Safari and kinda feels like it's spawning at pixel (0,0)

**To Reproduce**

1. Use the incident text box to paste a link (don't have to click post)
2. Notice textbox spawns in the very top left of the screen, partially obscured

**Expected behavior**

I'm not sure where the best UX place is for it to pop-up, but I know it's not where it currently is 😄 

**Screenshots**

![Screenshot 2024-02-05 at 5 03 15 PM](https://github.com/grafana/incident-community/assets/11779260/ea2eff91-f255-4edc-94a4-6c19b5141467)

**Relevant system information**
Grafana v10.4.0-65875 (b758b91e84)
Incident v1.38.0
Safari 17.3 (19617.2.4.11.8)
Chrome 121.0.6167.139

**Comment by clord** [comment]
We have a fix for this in the pipeline. an upcoming release will include the fix. thanks for reporting!
